server:
  port: 8080
  shutdown: graceful
management:
  endpoint:
    shutdown:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
spring:
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  security:
    user:
      name: admin
      password: admin
      roles: SUPERUSER
